### ISSUE TITLE
Add serde property to set case sensitivity  

### ISSUE THREAD

**Issue by peteford1** [amzn/ion-hive-serde#51]
Can I please get a serde property to set case sensitivity for elements not defined with path_extractor?    For fields defined with the path_extractor this is defined via setting the serde property  ion.path_extractor.case_sensitive="true/false" 

In the example below I generate a file and 2 hive tables.  Configuring the value should allow me to return both of the ims_state structs in the query "select * from case_2;".  
 
--generate ion file to test case sensitivity 

echo "{domain_id:11111,item_id:\"0061137456\",version_time:2012-01-26T17:52:54.749Z,marketplace_id:1,marketplace_id_temp:2,marketplace_id_temp_1:3,product:{merchant_suggested_asin:[{value:\"0061137456-A\",ims_state:{changed_at_version:6681,value:tombstoned}},{value:\"0061137456-B\",ims_STATE:{changed_at_version:6681,value:tombstoned}}]}}" > case.ion

--move to hadoop
hadoop fs -mkdir /user/data/case
hadoop fs -put -f case.ion /user/data/case/case.ion
hive 

--generate hive table without case sensitivity defined (document suggests it defaults to true"
CREATE EXTERNAL TABLE case_1(item_id STRING,domain_id INT,marketplace_id INT,version_time timestamp, product struct<merchant_suggested_asin:array<struct<value:string,ims_state:struct<value:string,changed_at_version:INT>>>>) ROW FORMAT SERDE 'com.amazon.ionhiveserde.IonHiveSerDe' STORED AS INPUTFORMAT 'com.amazon.ionhiveserde.formats.IonInputFormat' OUTPUTFORMAT 'com.amazon.ionhiveserde.formats.IonOutputFormat' LOCATION '/user/data/case';

CREATE EXTERNAL TABLE case_2(item_id STRING,domain_id INT,marketplace_id INT,version_time timestamp, product struct<merchant_suggested_asin:array<struct<value:string,ims_state:struct<value:string,changed_at_version:INT>>>>) ROW FORMAT SERDE 'com.amazon.ionhiveserde.IonHiveSerDe'  WITH SERDEPROPERTIES ("ion.path_extractor.case_sensitive"="false") STORED AS INPUTFORMAT 'com.amazon.ionhiveserde.formats.IonInputFormat' OUTPUTFORMAT 'com.amazon.ionhiveserde.formats.IonOutputFormat' LOCATION '/user/data/case';

**Comment by cheqianh** [comment]
Above commit fix this.
