### ISSUE TITLE
Z-Standard Compression Codec support

### ISSUE THREAD

**Issue by cheqianh** [amzn/ion-hive-serde#54]
Currently, the Ion-Hive serde only supports gzip compressed files, which is done natively in the IonReader/IonWriter from IonJava. It would be good to support Z-Standard compression codec too.

**Comment by jacob-stein** [comment]
Just to add a quick note to this: implementation using the compression codec abstraction (https://hadoop.apache.org/docs/r3.0.0/api/org/apache/hadoop/io/compress/CompressionCodec.html) should be extensible to additional compression formats.

**Comment by cheqianh** [comment]
For reference, here are two PRs addressing this.
Write support: https://github.com/amzn/ion-hive-serde/pull/73
Read support: https://github.com/amzn/ion-hive-serde/pull/62
